/**
Copyright (c) 2018

Original Author(s) of this File:
  Warren Weber, 10/26/18, University of Minnesota
*/

#ifndef MIA_COMMAND_LINE_PROCESSOR_H_
#define MIA_COMMAND_LINE_PROCESSOR_H_

#include <vector>
#include <string>
#include "imagetools/image_editor.h"
#include "mia/image_editor_commands.h"
#include "imagetools/convolution_filter_motion_blur.h"

namespace image_tools {
/**
@brief The CommandLineProcessor class takes in an array of char arrays, where
each array is a command value generated by the user. These commands are
processed on a passed png file and output to a passed png file.*/
class CommandLineProcessor {
 public:
  CommandLineProcessor();
  /**
  @brief Processes an array of char pointers and count integer to apply
  image_editor_commands in the control model*/
  void ProcessCommandLine(int argc, char* argv[]);

  bool is_valid_commands_() {return valid_cmds_;}

 private:
  std::vector<ImageEditorCommand*> cmd_v_;
  ImageEditor image_edit_;
  float red_chan_;
  float green_chan_;
  float blue_chan_;
  ConvolutionFilterMotionBlur::BlurDir blur_dir_;
  bool valid_cmds_;
  std::string help_message_;
};
}  // namespace image_tools
#endif     // MIA_COMMAND_LINE_PROCESSOR_H_
